name: Add Version Comment

on:

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  version-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Modify version worker-vless.js
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: src/worker-vless.js
          body: "Last update: {{date:YYYY-MM-DD HH:mm:ss}} UTC - NiREvil - version base on commit ${{ github.sha }} "
          message: "Version Comment add successfully"
      - name: Modify version worker-with-socks5-experimental.js
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: src/worker-with-socks5-experimental.js
          body: "Last update {{date:YYYY-MM-DD HH:mm:ss}} UTC - NiREvil - version base on commit ${{ github.sha }} "
          message: "Version Comment add successfully"
